---
name: Release and upload Qubership Envgene Templates to Maven Central
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: '0.0.0.1'
        type: string
        description: 'Release version (e.g., 0.0.0.1)'
      java_version:
        required: false
        type: string
        default: "21"
        description: 'Java version (e.g., 21)'
jobs:
  check-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Input parameters
        run: |
          echo "Version: ${{ github.event.inputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "Java version: ${{ github.event.inputs.java_version }}" >> $GITHUB_STEP_SUMMARY
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check if tag exists
        id: check_tag
        uses: netcracker/qubership-workflow-hub/actions/tag-checker@main
        with:
          tag: 'v${{ github.event.inputs.version }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Output result
        run: |
          echo "Tag exists: ${{ steps.check_tag.outputs.exists }}"
          echo "Tag name: v${{ github.event.inputs.version }}"
      - name: Fail if tag exists
        if: steps.check_tag.outputs.exists == 'true'
        run: |
          echo "Tag already exists: v${{ github.event.inputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "Tag already exists: v${{ github.event.inputs.version }}"
          exit 1
  update-pom-version:
    needs: [check-tag]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update pom.xml
        uses: Netcracker/qubership-workflow-hub/actions/update-pom-release@main
        with:
          new_value: ${{ github.event.inputs.version }}
      - name: Commit Changes
        uses: Netcracker/qubership-workflow-hub/actions/commit-and-push@main
        with:
          commit_message: "Update pom.xml version to ${{ github.event.inputs.version }}"
  upload_to_maven_central:
    needs: [update-pom-version]
    uses: Netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@main
    with:
      maven_command: "--batch-mode deploy"
      java_version: ${{ github.event.inputs.java_version }}
      version: ${{ github.event.inputs.version }}
    secrets:
      maven_username: ${{ secrets.MAVEN_USER }}
      maven_password: ${{ secrets.MAVEN_PASSWORD }}
      maven_gpg_passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      maven_gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
  github-release:
    needs: [upload_to_maven_central]
    uses: Netcracker/qubership-workflow-hub/.github/workflows/release-drafter.yml@main
    with:
      version: ${{ github.event.inputs.version }}
      publish: false